### ISSUE TITLE
ライセンスに関して

### ISSUE THREAD

**Issue by k-washi** [morikatron/snippet#1]
こちらで公開しているプログラムのライセンスを教えていただけないでしょうか？
または、基本的にライセンスはなしで、著作権保護上、改変を許していないのでしょうか？

ご回答の程よろしくお願いたします。

**Comment by ma2bara** [comment]
@k-washi さん
こんにちは。
ながらくお待たせいたしました。
本リポジトリはMITライセンスといたします。
どうぞよろしくお願いします。
